version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:16.17.0
    resource_class: small

jobs:
  build:
    working_directory: ~/repo
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  unit-tests:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          working_directory: .
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/
      - persist_to_workspace:
          root: .
          paths:
            - reports
            - coverage
            - test-report.xml

  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync build s3://pedrovanali --delete --exact-timestamps;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - unit-tests: 
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main